### ISSUE TITLE
Fails to work when run as root on a Debian-based system

### ISSUE THREAD

**Issue by BitJam** [Ventto/lux#1]
I fixed this by removing the quotes from around ${SUDO_USER} on line 103.  Maybe more should be done.
 
  -        if ! id -nG "${SUDO_USER}" | grep video > /dev/null ; then
  +        if ! id -nG ${SUDO_USER} | grep video > /dev/null ; then

**Comment by Ventto** [comment]
Effectively, thanks for contribution.
