### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by ghost** [Ventto/lux#5]
While the projects itself is licensed under the MIT license, the script [mentions GPLv3+][sh-license] as its license. [This commit][gpl2mit] tells the script should be upgraded to reflect that.

[sh-license]: https://github.com/Ventto/lux/blob/master/lux.sh#L59-L63
[gpl2mit]: https://github.com/Ventto/lux/commit/1ec3aad67cd74ab7801529feaa4027d8cb9b06a8#diff-9879d6db96fd29134fc802214163b95a

**Comment by Ventto** [comment]
@ghost,
Thanks for contribution.
My apologies for the delay.
